title: PremiLab-Math
description: We are dedicated to utilizing AI to solve mathematical problems.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
